spring:
  profiles:
    active:
      - dev
mybatis:
  mapper-locations: classpath*:com/opensource/soft/BlogServer/api/**/mapper/*Mapper.xml
  type-aliases-package: com.chinaopensource.soft.BlogServer.api
  
pagehelper:
  helper-dialect: mysql
server:
  servlet:
    context-path: /api
    